### ISSUE TITLE
Markdown-Support

### ISSUE THREAD

**Issue by Lukas2112** [sebinside/WissenschaftlichesSchreiben-Schnelleinstieg#15]
Could the template be adapted so that it can also be used with markdown via pandoc?

**Comment by sebinside** [comment]
What template are you talking about?

**Comment by Lukas2112** [comment]
Basically the template to get into scientific writing quickly, I imagine? Don't know LaTex in detail enough to assess it, unfortunately. 

My thought was that important things (authorship name, date, title, subtitle, etc.) are recorded in the metadata of a Markdown file and can then simply be written below.

**Comment by sebinside** [comment]
Still don't understand. If you're looking to work with markdown and latex have a look at [pandoc](https://pandoc.org/). Otherwise, there are plenty of templates, e.g., over at [Overleaf](https://www.overleaf.com/latex/templates).

**Comment by linux-lukas** [comment]
How much effort would it take to make the template more dynamic so that it can be filled via either latex or pandoc metadata?
