### ISSUE TITLE
Programm-Hinweis zu 5.2

### ISSUE THREAD

**Issue by pickbreaker** [sebinside/WissenschaftlichesSchreiben-Schnelleinstieg#4]
Bei uns am Institut (Julius-Maximilians-Universität Würzburg - Institut für Informatik) wird für Präsentationen häufig das Open-Source-Tool ipe (https://ipe.otfried.org) verwendet. Das Tool ist einerseits ein WYSIWYG-Tool, andererseits benutzt das Tool intern Latex und überall in der Präsentation kann Latex verwendet werden, ohne dass man den Vorteil des intuitiveren Designens verliert. Leider ist die GUI etwas gewöhnungsbedürftig. Eine Vorlage für das KIT mit kurzer Einführung kann unter https://i11www.iti.kit.edu/information/ipe_tutorial gefunden werden.

**Comment by sebinside** [comment]
Vielen Dank für den Hinweis, das Tool kannte ich auch noch nicht. Der Kürze halber neige ich eher dazu, es nicht mit aufzunehmen, da ich für die richtige Erklärung wohl 1-2 Sätze brauche - Platz den ich aktuell nicht mehr habe, um im 3-Seiten Limit zu bleiben...
